[workspace]
members = [
    "0_common/graph",
    "0_common/arg",
    "1_nn",
    "2_mem",
    "3_exec",
    "example",
]
resolver = "3"
package.edition = "2024"

[workspace.dependencies]
tensor = { git = "https://github.com/YdrMaster/tensor", rev = "c0b4893" }
