[package]
name = "infini-nn"
version = "0.0.1"
edition = "2024"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
digit-layout = "0.3"
ndarray-layout = "0.2"
itertools = "0.14"

[dev-dependencies]
patricia_tree = "0.9"
