[package]
name = "nural-network-machine"
version.workspace = true
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
digit-layout.workspace = true
ndarray-layout.workspace = true
downcast-rs = "2.0"
