[package]
name = "nnvm"
version = "0.0.0"
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
tensor = { git = "https://github.com/YdrMaster/tensor", rev = "66450a9" }
rwrc = { git = "https://github.com/YdrMaster/rwrc", rev = "765656e" }
