[package]
name = "nnvm"
version = "0.0.0"
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
tensor.path = "../tensor"
rwrc = { git = "https://github.com/YdrMaster/rwrc", rev = "3cd2fbd" }
