[package]
name = "test-vm"
version.workspace = true
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
vm.workspace = true
digit-layout.workspace = true
patricia_tree.workspace = true
