[package]
name = "mem"
version = "0.0.0"
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
graph.path = "../0_common/graph"
arg.path = "../0_common/arg"
tensor = { git = "https://github.com/YdrMaster/tensor", rev = "66450a9" }
