[package]
name = "nn"
version.workspace = true
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
vm.workspace = true
digit-layout.workspace = true
itertools.workspace = true

[dev-dependencies]
test-vm.path = "../test-vm"
