[package]
name = "nn"
version = "0.0.1"
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
vm.workspace = true
digit-layout.workspace = true
itertools = "0.14"

[dev-dependencies]
test-vm.path = "../test-vm"
